# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=512)),
                ('file_name', models.TextField(max_length=256)),
                ('file_size', models.BigIntegerField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.TextField(max_length=120, unique=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sequencingfile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcgs.SequencingRun'),
        ),
    ]
