# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingfile',
            name='user_name',
            field=models.TextField(default=b'', max_length=256),
        ),
    ]
