#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'gcloud-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 3

# KUBERNETES_VERSION: '1.11.2-gke.18'
KUBERNETES_VERSION: '1.12.8-gke.10'

CLUSTER_EXTERNAL_IP: '35.197.185.153'
CLUSTER_HOSTNAME: 'seqr-dev.mcri.edu.au'
BASE_URL: 'https://seqr-dev.mcri.edu.au'

MONGO_SERVICE_EXTERNAL_IP: 10.128.0.3  # broad-seqr
MONGO_SERVICE_EXTERNAL_PORT: 27017

#ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.16.0.3
#ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200

ELASTICSEARCH_SERVICE_EXTERNAL_IP: {{ HOST_MACHINE_IP }}  # default assumes elasticsearch is running on the same machine as minikube
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200



SEQR_SERVICE_NODE_PORT: 30003   # after deployment, seqr will be accessible at http://$(minikube ip):$SEQR_SERVICE_NODE_PORT . Node port range starts at 30000

GCLOUD_PROJECT: 'mcri-01'
GCLOUD_ZONE: 'australia-southeast1-b'

SEQR_GIT_BRANCH: 'master'

SEQR_POD_MEMORY_LIMIT: 15Gi
REDIS_POD_MEMORY_LIMIT: 8Gi
PHENOTIPS_POD_MEMORY_LIMIT: 3Gi

UPLOADED_PEDIGREE_FILE_RECIPIENTS: ''

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: gcloud-dev

DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'
