# kubectl get services elasticsearch-data -o=yaml | yq -Y 'del(.status) | del(.metadata.annotations) | del(.metadata.generation) | del(.metadata.creationTimestamp) | del(.metadata.resourceVersion) | del(.metadata.selfLink) | del(.metadata.uid)'

apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: data
  name: elasticsearch-data
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    component: elasticsearch
    role: data
  sessionAffinity: None
  type: ClusterIP
