# kubectl get services elasticsearch-ingest -o=yaml | yq -Y 'del(.status) | del(.metadata.annotations) | del(.metadata.generation) | del(.metadata.creationTimestamp) | del(.metadata.resourceVersion) | del(.metadata.selfLink) | del(.metadata.uid) | del(.spec.clusterIP)'

apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: ingest
  name: elasticsearch-ingest
  namespace: default
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    component: elasticsearch
    role: ingest
  sessionAffinity: None
  type: ClusterIP
