apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-master-0
spec:
  storageClassName: "standard-expandable"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-es-master-es-master-0
  gcePersistentDisk:
    pdName: pd-es-master-0
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-master-1
spec:
  storageClassName: "standard-expandable"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-es-master-es-master-1
  gcePersistentDisk:
    pdName: pd-es-master-1
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data-0
spec:
  storageClassName: "standard-expandable"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-es-data-es-data-0
  gcePersistentDisk:
    pdName: pd-es-data-0
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data-1
spec:
  storageClassName: "standard-expandable"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-es-data-es-data-1
  gcePersistentDisk:
    pdName: pd-es-data-1
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data-2
spec:
  storageClassName: "standard-expandable"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-es-data-es-data-2
  gcePersistentDisk:
    pdName: pd-es-data-2
    fsType: ext4
