# kubectl get services elasticsearch -o=yaml | yq -Y 'del(.status) | del(.metadata.annotations) | del(.metadata.generation) | del(.metadata.creationTimestamp) | del(.metadata.resourceVersion) | del(.metadata.selfLink) | del(.metadata.uid) | del(.spec.clusterIP)'

apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: data
  name: elasticsearch
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30100
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    component: elasticsearch
    role: data
  sessionAffinity: None
  type: NodePort
